export const markers = [
    {
        id : 1, 
        img : "", 
        symbol : "https://static.arcgis.com/images/Symbols/Shapes/BlackStarLargeB.png", 
        description : "", 
        longitude : 1, 
        latitude : 2,
    },
    {
        id : 2, 
        img : "", 
        symbol : "https://static.arcgis.com/images/Symbols/Shapes/BlackStarLargeB.png", 
        description : "", 
        longitude : 1, 
        latitude : 2,
    },
    {
        id : 1, 
        img : "", 
        symbol : "https://static.arcgis.com/images/Symbols/Shapes/BlackStarLargeB.png", 
        description : "", 
        longitude : 1, 
        latitude : 2,
    },
    {
        id : 1, 
        img : "", 
        symbol : "https://static.arcgis.com/images/Symbols/Shapes/BlackStarLargeB.png", 
        description : "", 
        longitude : 1, 
        latitude : 2,
    },
    {
        id : 1, 
        img : "", 
        symbol : "https://static.arcgis.com/images/Symbols/Shapes/BlackStarLargeB.png", 
        description : "", 
        longitude : 1, 
        latitude : 2,
    },
    {
        id : 1, 
        img : "", 
        symbol : "https://static.arcgis.com/images/Symbols/Shapes/BlackStarLargeB.png", 
        description : "", 
        longitude : 1, 
        latitude : 2,
    },
    {
        id : 1, 
        img : "", 
        symbol : "https://static.arcgis.com/images/Symbols/Shapes/BlackStarLargeB.png", 
        description : "", 
        longitude : 1, 
        latitude : 2,
    },
    {
        id : 1, 
        img : "", 
        symbol : "https://static.arcgis.com/images/Symbols/Shapes/BlackStarLargeB.png", 
        description : "", 
        longitude : 1, 
        latitude : 2,
    },
    {
        id : 1, 
        img : "", 
        symbol : "https://static.arcgis.com/images/Symbols/Shapes/BlackStarLargeB.png", 
        description : "", 
        longitude : 1, 
        latitude : 2,
    },
    {
        id : 1, 
        img : "", 
        symbol : "https://static.arcgis.com/images/Symbols/Shapes/BlackStarLargeB.png", 
        description : "", 
        longitude : 1, 
        latitude : 2,
    },
    {
        id : 1, 
        img : "", 
        symbol : "https://static.arcgis.com/images/Symbols/Shapes/BlackStarLargeB.png", 
        description : "", 
        longitude : 1, 
        latitude : 2,
    },
    {
        id : 1, 
        img : "", 
        symbol : "https://static.arcgis.com/images/Symbols/Shapes/BlackStarLargeB.png", 
        description : "", 
        longitude : 1, 
        latitude : 2,
    },
    {
        id : 1, 
        img : "", 
        symbol : "https://static.arcgis.com/images/Symbols/Shapes/BlackStarLargeB.png", 
        description : "", 
        longitude : 1, 
        latitude : 2,
    },
    {
        id : 1, 
        img : "", 
        symbol : "https://static.arcgis.com/images/Symbols/Shapes/BlackStarLargeB.png", 
        description : "", 
        longitude : 1, 
        latitude : 2,
    },
    {
        id : 1, 
        img : "", 
        symbol : "https://static.arcgis.com/images/Symbols/Shapes/BlackStarLargeB.png", 
        description : "", 
        longitude : 1, 
        latitude : 2,
    },
    {
        id : 1, 
        img : "", 
        symbol : "https://static.arcgis.com/images/Symbols/Shapes/BlackStarLargeB.png", 
        description : "", 
        longitude : 1, 
        latitude : 2,
    },
    {
        id : 1, 
        img : "", 
        symbol : "https://static.arcgis.com/images/Symbols/Shapes/BlackStarLargeB.png", 
        description : "", 
        longitude : 1, 
        latitude : 2,
    },
    {
        id : 1, 
        img : "", 
        symbol : "https://static.arcgis.com/images/Symbols/Shapes/BlackStarLargeB.png", 
        description : "", 
        longitude : 1, 
        latitude : 2,
    },
    {
        id : 1, 
        img : "", 
        symbol : "https://static.arcgis.com/images/Symbols/Shapes/BlackStarLargeB.png", 
        description : "", 
        longitude : 1, 
        latitude : 2,
    },
    {
        id : 1, 
        img : "", 
        symbol : "https://static.arcgis.com/images/Symbols/Shapes/BlackStarLargeB.png", 
        description : "", 
        longitude : 1, 
        latitude : 2,
    }
]